# Swagger Coding Style Guidelines
# https://github.com/watson-developer-cloud/api-guidelines/blob/master/swagger-coding-style.md#model-names

# HTTP codes
# https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors

openapi: 3.0.0
info:
  version: 1.0.0
  title: connection-proposer-api
  description: Connection proposer API

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/martin.pospisil/connection-proposer-api/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/martin.pospisil/connection-browser/1.0.0
tags:
  - name: User
    description: Operations related to users
  - name: Connection-Design-Set
    description: Operations related to connection design sets
  - name: Connection-Design-Item
    description: Operations related to connection design items

# Reusable path, query, header and cookie parameters
components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
      
  schemas:
    UserRole:                  # Can be referenced as '#/components/schemas/UserRole'
      type: string
      enum:
        - engineer
        - lead-engineer
        - is-administrator
      description: role of the user   

    User:          # Can be referenced as '#/components/schemas/User'
      type: object
      description: information about the user
      properties:
        name:
          type: string
          description: name of the user
        role:
          $ref: '#/components/schemas/UserRole'    
    
    ConDesignSetId:   # Can be referenced as '#/components/schemas/ConDesignSetId'
      type: string
      format: uuid
      description: The unique identifier of the connection design set

    ConDesignItemId:   # Can be referenced as '#/components/schemas/ConDesignItemId'
      type: string
      format: uuid
      description: The unique identifier of the connection design item

    ConDesignSet:     # Can be referenced as '#/components/schemas/ConDesignSet'
      type: object
      description: information about the connection design set (a group of connection design items)
      properties:
        id:
          $ref: '#/components/schemas/ConDesignSetId'
        name:
          type: string
          description: name of the dataset
        description:
          type: string
          description: user friendly description of the connection design set
        owner:
          $ref: '#/components/schemas/UserRole'

    ConDesignItem:     # Can be referenced as '#/components/schemas/ConDesignItem'
      type: object
      description: Connection design item 
      properties:
        id:
           $ref: '#/components/schemas/ConDesignItemId'
        name:
          type: string
          description: name of the dataset
        description:
          type: string
          description: user friendly description of the connection design item
        version:
          type: string
          description: version of the miner which created this connection design item                  

    PublishWorkItem:          # Can be referenced as '#/components/schemas/PublishWorkItem'
      type: object
      description: Information about work item for the given publishing job. User can use this data for observing the status of this job.
      properties:
        job-id:
          type: string
          format: uuid
          description: The unique identifier of the publishing job
   

    ConnectionPublisingMetaData:     # Can be referenced as '#/components/schemas/ConnectionPublisingMetaData'
      type: object
      description: Additional meta data about the connection which an user wants to publish to the connection design set
      properties:
        connection-id:
          type: string
          format: uuid
          description: The id of the published connection in the ideacon project
        name:
          type: string
          description: The name of the new connection design item

  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    DesignSetIdParam:      # Can be referenced via '#/components/parameters/DesignSetIdParam'
      name: id
      in: query
      description: The ID of the required connection design set
      required: true
      schema:
        $ref: '#/components/schemas/ConDesignSetId'
        
    DesignItemIdParam:      # Can be referenced via '#/components/parameters/DesignItemIdParam'
      name: id
      in: query
      description: The ID of the required connection design item
      required: true
      schema:
        $ref: '#/components/schemas/ConDesignItemId'

  #-------------------------------
  # Reusable requestBodies
  #-------------------------------
  requestBodies:

    ConDesignSetBody:      # Can be referenced via '#/components/requestBodies/ConDesignSetBody'
      description: An object containing connection design set information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConDesignSet'

    ConDesignItemBody:      # Can be referenced via '#/components/requestBodies/ConDesignItemBody'
      description: An object containing connection design item information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConDesignItem'

  #-------------------------------
  # Reusable operation responses
  #-------------------------------
  responses:
    BadRequest:      # HTTP Error 400 Can be referenced via '#/components/responses/BadRequest'
      description: Bad Request

    Unauthorized:      # HTTP Error 401 Can be referenced via '#/components/responses/Unauthorized'
      description: Unauthorized user

    NotFound:      # HTTP Error 404 Can be referenced via '#/components/responses/NotFound'
      description: The specified resource was not found

    InternalError:      # HTTP rerror 500 Can be referenced via '#/components/responses/InternalError'
      description: Internal Server Error

security:
  - bearerAuth: []    

paths:
  /user:
    get:
      tags:
        - User
      summary: Get information about the current user
      operationId: getUser
      responses:
        '200':
          description: information about the current user
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/User'     

        '401':
          $ref: '#/components/responses/Unauthorized'

  /design-sets:
    get:
      tags:
        - Connection-Design-Set        
      summary: Get all available connection design sets for the current user
      operationId: getConDesignSets
      responses:
        '200':
          description: A list of available connection design sets for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/ConDesignSet'       

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'

  /design-set:
    get:
      summary: Get single connection design set by its unique id
      tags:
        - Connection-Design-Set        
      operationId: getConDesignSet
      parameters:
        - $ref: '#/components/parameters/DesignSetIdParam'
      responses:
        '200':
          description: Information about connection design set
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/ConDesignSet'      

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete the connection design set
      description: Delete the single connection design set which is defined by passed its unique id
      tags:
        - Connection-Design-Set        
      operationId: deleteConDesignSet
      parameters:
        - $ref: '#/components/parameters/DesignSetIdParam'      
      responses:
        '200':
          description: OK

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create or modify the connection design set
      description: Create or modify the connection design set and return the updated instance from the database
      tags:
        - Connection-Design-Set        
      operationId: createConDesignSet
      requestBody:
        $ref: '#/components/requestBodies/ConDesignSetBody'
      responses:
        '200':
          description: Information about the modified connection design set
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/ConDesignSet' 
        '400':
          $ref: '#/components/responses/BadRequest'

        '401':
          $ref: '#/components/responses/Unauthorized'
             
               
  /design-items:
    get:
      tags:
        -  Connection-Design-Item        
      summary: Get all connection design items from the given connection design set
      operationId: getConDesignItems
      parameters:
        - $ref: '#/components/parameters/DesignSetIdParam'        
      responses:
        '200':
          description: A list of all connection design items from the given connection design set
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/ConDesignItem'       

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'


  /project-publish:
    post:
      tags:
        - Connection-Design-Item     
      summary: Publish connection design items
      description: Publish selected connection design items from Idea connection project to the given connection design set
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                publishing-items:
                  type: array
                  items:
                    $ref: '#/components/schemas/ConnectionPublisingMetaData'
                conn-project:
                  description: Idea connection project containing connections for publishing
                  type: string
                  format: binary

      responses:
        '200':
          description: Identifier of the publiblish work item. It can be used for observing the status of publishing.
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/PublishWorkItem'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /design-item:
    get:
      summary: Get the connection design item
      description: Get data of the single design item which is given by its unique id
      tags:
        - Connection-Design-Item        
      operationId: getConDesignItem
      parameters:
        - $ref: '#/components/parameters/DesignItemIdParam'
      responses:
        '200':
          description: Information about the connection design item
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/ConDesignItem'      

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete the connection design item
      description: Delete the single design item which is given by its unique id
      tags:
        - Connection-Design-Item        
      operationId: deleteConDesignItem
      parameters:
        - $ref: '#/components/parameters/DesignItemIdParam'
      responses:
        '200':
          description: OK

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'

    post:
      summary: Create or modify the connection design item
      description: Create or modify the connection design item and return the updated instance from the database
      tags:
        - Connection-Design-Item        
      operationId: postConDesignItem
      requestBody:
        $ref: '#/components/requestBodies/ConDesignItemBody'
      responses:
        '200':
          description: Information about modified connection design item
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/ConDesignItem' 
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
