# Swagger Coding Style Guidelines
# https://github.com/watson-developer-cloud/api-guidelines/blob/master/swagger-coding-style.md#model-names

# HTTP codes
# https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_client_errors

openapi: 3.0.0
info:
  version: 1.0.0
  title: connection-proposer-api
  description: Connection proposer API

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/martin.pospisil/connection-proposer-api/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/martin.pospisil/connection-browser/1.0.0
tags:
  - name: user
    description: Operations related to users
  - name: conDesignSet
    description: Operations related to connection design sets
  - name: conDesignItem
    description: Operations related to connection design items

# Reusable path, query, header and cookie parameters
components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
      
  schemas:
    UserRole:                  # Can be referenced as '#/components/schemas/UserRole'
      type: string
      enum:
        - engineer
        - lead-engineer
        - is-administrator
      description: role of the user   

    User:          # Can be referenced as '#/components/schemas/User'
      type: object
      description: information about the user
      properties:
        name:
          type: string
          description: name of the user
        role:
          $ref: '#/components/schemas/UserRole'    
    
    ConDesignSetId:   # Can be referenced as '#/components/schemas/ConDesignSetId'
      type: string
      format: uuid
      description: The unique identifier of the connection design set

    ConDesignItemId:   # Can be referenced as '#/components/schemas/ConDesignItemId'
      type: string
      format: uuid
      description: The unique identifier of the connection design item

    ConDesignSet:     # Can be referenced as '#/components/schemas/ConDesignSet'
      type: object
      description: information about the connection design set (a group of connection design items)
      properties:
        id:
          $ref: '#/components/schemas/ConDesignSetId'
        name:
          type: string
          description: name of the dataset
        description:
          type: string
          description: user friendly description of the connection design set
        owner:
          $ref: '#/components/schemas/UserRole'

    ConDesignItem:     # Can be referenced as '#/components/schemas/ConDesignItem'
      type: object
      description: information    
      properties:
        id:
           $ref: '#/components/schemas/ConDesignItemId'
      
  #-------------------------------
  # Reusable operation parameters
  #-------------------------------
  parameters:
    designSetIdParam:      # Can be referenced via '#/components/parameters/designSetIdParam'
      name: id
      in: query
      description: The ID of the required connection design set
      required: true
      schema:
        $ref: '#/components/schemas/ConDesignItemId'

  responses:
    Unauthorized:      # HTTP Error 401 Can be referenced via '#/components/responses/Unauthorized'
      description: Unauthorized user

    NotFound:      # HTTP Error 404 Can be referenced via '#/components/responses/NotFound'
      description: The specified resource was not found

    InternalError:      # HTTP rerror 500 Can be referenced via '#/components/responses/InternalError'
      description: Internal Server Error

security:
  - bearerAuth: []    

paths:
  /user:
    get:
      tags:
        - user
      summary: Get information about the current user
      operationId: getUser
      responses:
        '200':
          description: information about the current user
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/User'     

        '401':
          $ref: '#/components/responses/Unauthorized'

  /conDesignSet:
    get:
      tags:
        - conDesignSet        
      summary: Get all available connection design sets for the current user
      operationId: getConDesignSets
      responses:
        '200':
          description: A list of available connection design sets for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/ConDesignSet'       

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'         
          
  /conDesignItems:
    get:
      tags:
        - conDesignItem        
      summary: Get all connection design items from the given connection design set
      operationId: getConDesignItems
      parameters:
        - $ref: '#/components/parameters/designSetIdParam'        
      responses:
        '200':
          description: A list of all connection design items from the given connection design set
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/ConDesignItem'       

        '401':
          $ref: '#/components/responses/Unauthorized'

        '404':
          $ref: '#/components/responses/NotFound'