/*
 * connection-browser
 *
 * Connection browser API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// information about the user
    /// </summary>
    [DataContract]
    public partial class UserMetaData : IEquatable<UserMetaData>
    { 
        /// <summary>
        /// name of the user
        /// </summary>
        /// <value>name of the user</value>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// role of the user
        /// </summary>
        /// <value>role of the user</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum RoleEnum
        {
            /// <summary>
            /// Enum EngineerEnum for engineer
            /// </summary>
            [EnumMember(Value = "engineer")]
            EngineerEnum = 0,
            /// <summary>
            /// Enum LeadengineerEnum for leadengineer
            /// </summary>
            [EnumMember(Value = "leadengineer")]
            LeadengineerEnum = 1,
            /// <summary>
            /// Enum IsadministratorEnum for isadministrator
            /// </summary>
            [EnumMember(Value = "isadministrator")]
            IsadministratorEnum = 2        }

        /// <summary>
        /// role of the user
        /// </summary>
        /// <value>role of the user</value>
        [DataMember(Name="role")]
        public RoleEnum? Role { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserMetaData {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Role: ").Append(Role).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserMetaData)obj);
        }

        /// <summary>
        /// Returns true if UserMetaData instances are equal
        /// </summary>
        /// <param name="other">Instance of UserMetaData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserMetaData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Role == other.Role ||
                    Role != null &&
                    Role.Equals(other.Role)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Role != null)
                    hashCode = hashCode * 59 + Role.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(UserMetaData left, UserMetaData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserMetaData left, UserMetaData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
